#!/usr/bin/env python
"""Evaluation aggregation is generated by 06_run_estimators.py.
This stage reports the aggregate file location for compatibility with the old workflow.
"""
import argparse
from pathlib import Path
from casbl_jadce.config import load_config
p = argparse.ArgumentParser(); p.add_argument("--config", default="configs/quick.yaml")
a = p.parse_args(); cfg = load_config(a.config)
print(Path(cfg["run"]["output_dir"]) / "evaluation" / "aggregate.csv")
